package by.bsu.command;

public enum CommandName {
    SEARCH_CARS, NO_SUCH_COMMAND, REGISTER_ACCOUNT, LOGIN, PRE_ORDER,
    SUBMIT_ORDER, LOGOUT, MYACCOUNT, SHOW_ACCOUNTS, DELETE_ORDER, SHOW_CARS, ADD_CAR, DELETE_CAR,
    SHOW_ORDERS, CHANGE_LANG, CHANGE_EMAIL, CHANGE_PASS
}
